# Generated by Django 5.2.14 on 2026-05-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО Клиента')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('loyalty_level', models.CharField(choices=[('none', 'Базовый (0%)'), ('bronze', 'Бронза (5%)'), ('silver', 'Серебро (10%)'), ('gold', 'Золото (15%)')], default='none', max_length=20, verbose_name='Уровень лояльности')),
                ('bonuses_balance', models.IntegerField(default=0, verbose_name='Баланс бонусов')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Всего потрачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='CoffeeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название блюда/напитка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розничная цена')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL изображения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен (в меню)')),
            ],
            options={
                'verbose_name': 'Товар меню',
                'verbose_name_plural': 'Меню (Товары)',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование ингредиента')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Текущий остаток')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('min_threshold', models.DecimalField(decimal_places=3, default=1.0, max_digits=10, verbose_name='Критический остаток')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Себестоимость единицы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Ингредиент склада',
                'verbose_name_plural': 'Склад (Ингредиенты)',
            },
        ),
        migrations.CreateModel(
            name='CommunicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Звонок'), ('email', 'Email'), ('meeting', 'Личная встреча'), ('chat', 'Чат / Мессенджер')], default='call', max_length=20, verbose_name='Тип связи')),
                ('content', models.TextField(verbose_name='Содержание разговора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата коммуникации')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='app.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'История коммуникации',
                'verbose_name_plural': 'Истории коммуникаций',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push')], default='sms', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('completed', 'Выполнен'), ('cancelled', 'Отклонен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма без скидки')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Скидка')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('bonuses_used', models.IntegerField(default=0, verbose_name='Списано бонусов')),
                ('bonuses_earned', models.IntegerField(default=0, verbose_name='Начислено бонусов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='app.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Принял заказ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.coffeeproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inflow', 'Оприходование'), ('write_off', 'Списание')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина / Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='app.inventoryitem', verbose_name='Ингредиент')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Операция по складу',
                'verbose_name_plural': 'История операций склада',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('director', 'Руководитель')], default='manager', max_length=20, verbose_name='Роль')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Необходимое количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_used_in', to='app.inventoryitem', verbose_name='Ингредиент склада')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='app.coffeeproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Рецепт товара',
                'verbose_name_plural': 'Рецепты товаров',
                'unique_together': {('product', 'item')},
            },
        ),
    ]
